### ISSUE TITLE
Show the minimalist badge hover when using a mouse

### ISSUE THREAD

**Issue by SmokeyPSD** [OMGDuke/protondb-decky#70] opened 2023-05-22 13:52 UTC
Not sure what's going on, moved around some branches and didnt seem to change the behaviour, can no longer hover over the badge element as could before. Currently on steam os beta and client beta.

**Comment by OMGDuke** [comment] 2023-05-22 14:28
I'm on steam beta too, plugin version 1.0.11 and I'm able to hover them fine.

What other plugins do you have installed so I can try to recreate?

**Comment by SmokeyPSD** [comment] 2023-05-22 16:26
Thanks for replying!
I have,
Pause Games
Metadeck
SteamGridDB
Game Theme Music
Vibrantdeck
CSS Loader

**Comment by OMGDuke** [comment] 2023-05-22 16:40
I've installed all those plugins, I'm still able to navigate to the badge with the game pad and with touch. 

Perhaps it's a css theme you have with css loader? The only other thing I can reccomend is to uninstall some plugins and see if its still broken, if it works reinstall them one by one to find what's causing it.

**Comment by SmokeyPSD** [comment] 2023-05-22 16:45
thanks, I'll start with CSS Loader as that's prolly the most obvious
conflict going on

**Comment by OMGDuke** [comment] 2023-05-22 17:15
Wait a mouse? I'm not sure its even setup to show anything when hovered by a mouse. As long as it highlights when selected by gamepad and pressing A opens the protondb website then sounds like its working as intended

**Comment by SmokeyPSD** [comment] 2023-05-22 17:17
oh really? I swear it did before. I'm currently using the deck setup into a
hub with a external screen etc.

**Comment by OMGDuke** [comment] 2023-05-22 17:17
Ok just tried with a mouse it does work for me. Hovering the button makes it go slightly lighter, then clicking opens protondb

**Comment by OMGDuke** [comment] 2023-05-22 17:18
If you click on the protondb button does it open the protondb page?

**Comment by OMGDuke** [comment] 2023-05-22 17:24
Oh wait so by more info do you mean the badge being icon only, select it and it shows the badge text?

Thats an option by choosing minimalist badge then expand label on hover, however in this case "hover" really means selected with gamepad. A mouse hover doesn't count. I can look into adding this behaviour though

**Comment by SmokeyPSD** [comment] 2023-05-22 17:40
yeah exactly it. I think my brain between swapping between a hub and
handheld made me think it already was a function 🤣 thank you for your help

**Comment by OMGDuke** [comment] 2023-05-22 17:41
Sorry was misunderstanding on my part, I'll keep this issue live as it should be something I can add

**Comment by OMGDuke** [comment] 2024-08-25 12:21
Fixed in #81

**Closed by OMGDuke** 2024-08-25 12:21 UTC
Labels: enhancement
